// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-COu5UqPXC2TWZQvuz2C-Em5PtILPlQ',
    appId: '1:203360712356:web:2ac51ca22c85a9c0c81831',
    messagingSenderId: '203360712356',
    projectId: 'mind-mirror-3a38d',
    authDomain: 'mind-mirror-3a38d.firebaseapp.com',
    storageBucket: 'mind-mirror-3a38d.firebasestorage.app',
    measurementId: 'G-QJG4PLGR3T',
    databaseURL: 'https://mind-mirror-3a38d-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIG5lj2degoEwjx0RwD9qMyDh6Hl3DS5E',
    appId: '1:203360712356:android:0a4a43737a35d813c81831',
    messagingSenderId: '203360712356',
    projectId: 'mind-mirror-3a38d',
    storageBucket: 'mind-mirror-3a38d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2nSA9iOzZGOH0Xk8d0824SsCsg_JX-I8',
    appId: '1:203360712356:ios:51023bedb1eff5bec81831',
    messagingSenderId: '203360712356',
    projectId: 'mind-mirror-3a38d',
    storageBucket: 'mind-mirror-3a38d.firebasestorage.app',
    iosBundleId: 'com.example.mindMirror',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2nSA9iOzZGOH0Xk8d0824SsCsg_JX-I8',
    appId: '1:203360712356:ios:51023bedb1eff5bec81831',
    messagingSenderId: '203360712356',
    projectId: 'mind-mirror-3a38d',
    storageBucket: 'mind-mirror-3a38d.firebasestorage.app',
    iosBundleId: 'com.example.mindMirror',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb-COu5UqPXC2TWZQvuz2C-Em5PtILPlQ',
    appId: '1:203360712356:web:6be8e56fdf58421dc81831',
    messagingSenderId: '203360712356',
    projectId: 'mind-mirror-3a38d',
    authDomain: 'mind-mirror-3a38d.firebaseapp.com',
    storageBucket: 'mind-mirror-3a38d.firebasestorage.app',
    measurementId: 'G-2X35FWVN03',
  );
}
